/**
 * This code was generated by Builder.io.
 */
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavComponent } from '../nav/nav.component';
import { BookshelfComponent } from '../bookshelf/bookshelf.component';
import { HeaderSignComponent } from '../header-sign/header-sign.component';
import { UserSignComponent } from '../user-sign/user-sign.component';
import { UserNavComponent } from '../Users/user-nav/user-nav.component';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
  standalone: true,
  imports: [CommonModule, NavComponent, BookshelfComponent, HeaderSignComponent, UserSignComponent]
})
export class HeaderComponent {
    userNavOpen = false;
}